//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmailServiceReference
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://portal.yabatech.edu.ng/", ConfigurationName="EmailServiceReference.yctoutserviceSoap")]
    public interface yctoutserviceSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://portal.yabatech.edu.ng/retschoolfee", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<double> retschoolfeeAsync(string matricno);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://portal.yabatech.edu.ng/getpayments", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<EmailServiceReference.getpaymentsResponseGetpaymentsResult> getpaymentsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://portal.yabatech.edu.ng/get_image", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> get_imageAsync(string matricno);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://portal.yabatech.edu.ng/sendmail", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<EmailServiceReference.sendmailResponse> sendmailAsync(EmailServiceReference.sendmailRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://portal.yabatech.edu.ng/")]
    public partial class getpaymentsResponseGetpaymentsResult
    {
        
        private System.Xml.XmlElement[] anyField;
        
        private System.Xml.XmlElement any1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Namespace="http://www.w3.org/2001/XMLSchema", Order=0)]
        public System.Xml.XmlElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Namespace="urn:schemas-microsoft-com:xml-diffgram-v1", Order=1)]
        public System.Xml.XmlElement Any1
        {
            get
            {
                return this.any1Field;
            }
            set
            {
                this.any1Field = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sendmail", WrapperNamespace="http://portal.yabatech.edu.ng/", IsWrapped=true)]
    public partial class sendmailRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://portal.yabatech.edu.ng/", Order=0)]
        public string email;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://portal.yabatech.edu.ng/", Order=1)]
        public string matricno;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://portal.yabatech.edu.ng/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] byteArray;
        
        public sendmailRequest()
        {
        }
        
        public sendmailRequest(string email, string matricno, byte[] byteArray)
        {
            this.email = email;
            this.matricno = matricno;
            this.byteArray = byteArray;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sendmailResponse", WrapperNamespace="http://portal.yabatech.edu.ng/", IsWrapped=true)]
    public partial class sendmailResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://portal.yabatech.edu.ng/", Order=0)]
        public string sendmailResult;
        
        public sendmailResponse()
        {
        }
        
        public sendmailResponse(string sendmailResult)
        {
            this.sendmailResult = sendmailResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface yctoutserviceSoapChannel : EmailServiceReference.yctoutserviceSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class yctoutserviceSoapClient : System.ServiceModel.ClientBase<EmailServiceReference.yctoutserviceSoap>, EmailServiceReference.yctoutserviceSoap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public yctoutserviceSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(yctoutserviceSoapClient.GetBindingForEndpoint(endpointConfiguration), yctoutserviceSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public yctoutserviceSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(yctoutserviceSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public yctoutserviceSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(yctoutserviceSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public yctoutserviceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<double> retschoolfeeAsync(string matricno)
        {
            return base.Channel.retschoolfeeAsync(matricno);
        }
        
        public System.Threading.Tasks.Task<EmailServiceReference.getpaymentsResponseGetpaymentsResult> getpaymentsAsync()
        {
            return base.Channel.getpaymentsAsync();
        }
        
        public System.Threading.Tasks.Task<string> get_imageAsync(string matricno)
        {
            return base.Channel.get_imageAsync(matricno);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EmailServiceReference.sendmailResponse> EmailServiceReference.yctoutserviceSoap.sendmailAsync(EmailServiceReference.sendmailRequest request)
        {
            return base.Channel.sendmailAsync(request);
        }
        
        public System.Threading.Tasks.Task<EmailServiceReference.sendmailResponse> sendmailAsync(string email, string matricno, byte[] byteArray)
        {
            EmailServiceReference.sendmailRequest inValue = new EmailServiceReference.sendmailRequest();
            inValue.email = email;
            inValue.matricno = matricno;
            inValue.byteArray = byteArray;
            return ((EmailServiceReference.yctoutserviceSoap)(this)).sendmailAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.yctoutserviceSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.yctoutserviceSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpsTransportBindingElement httpsBindingElement = new System.ServiceModel.Channels.HttpsTransportBindingElement();
                httpsBindingElement.AllowCookies = true;
                httpsBindingElement.MaxBufferSize = int.MaxValue;
                httpsBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpsBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.yctoutserviceSoap))
            {
                return new System.ServiceModel.EndpointAddress("https://portal.yabatech.edu.ng/transapi/yctoutservice.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.yctoutserviceSoap12))
            {
                return new System.ServiceModel.EndpointAddress("https://portal.yabatech.edu.ng/transapi/yctoutservice.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            yctoutserviceSoap,
            
            yctoutserviceSoap12,
        }
    }
}
